name: Deploy to Storefrontcloud
on:
  push:
    branches:
      - master
  release:
    types: [published]
env:
  CANARY_URL: https://shopware-pwa-canary.storefrontcloud.io
  RELEASE_URL: https://shopware-pwa.storefrontcloud.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup variables
        run: |
          echo ::set-env name=DEPLOY_URL::$([[ "${{github.event_name}}" == "release" ]] && echo "$RELEASE_URL" || echo "$CANARY_URL")
      - name: Should invoke release
        if: contains(github.event.head_commit.message, 'chore(release):')
        run: |
          echo "Start releasing packages"
      - name: debug
        run: |
          echo ${{github.event_name}}
      - name: conditional sth on push
        if: github.event_name == 'push'
        run: |
          echo "push was triggered!!!!"
          echo ${{ env.DEPLOY_URL }}
      - name: conditional sth on release
        if: github.event_name == 'release'
        run: |
          echo "release was triggered!!!!"
          echo ${{ env.DEPLOY_URL }}

