name: Deploy to Storefrontcloud
on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: debug
        run: |
          echo ${{github.event_name}}
      - name: conditional sth on push
        if: github.event_name == "push"
        run: |
          echo "push was triggered!!!!"
      - name: conditional sth on release
        if: github.event_name == "release"
        run: |
          echo "release was triggered!!!!"

